spring.application.name=Queoil

spring.datasource.url=jdbc:mysql://localhost:3306/queoil
spring.datasource.username=root
spring.datasource.password=Hopestreet94

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
